# .github/workflows/main.yml
name: CI / E2E Test

on:
  # 1. 每次 push 到 main 或指定功能分支時觸發
  push:
    branches:
      - main
      - feat/regularly-run-e2e

  # 2. 手動可以在 GitHub 網頁上按按鈕觸發
  workflow_dispatch:

  # 3. 定時排程（UTC 時區），以下範例是每天 01:21 執行一次
  schedule:
    - cron: '28 03 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    # 如果需要 Docker, 可以改成 container 模式或自己安裝
    # container:
    #  image: ghcr.io/puppeteer/puppeteer:24.3.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 若有安裝 Node.js 需求，就先把 Node 環境準備好
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      # 若要跑 E2E 測試，以下示範用 npm script
      - name: Run E2E Tests
        run: npm run test:e2e
